### ISSUE TITLE
Surround any text with "<<<" and ">>>" to escape the content

### ISSUE THREAD

**Issue by manofsteel2017** [OmerTu/GoogleHomeKodi#12]
I am confused? what do i put there? please help
i've been trying to get this to work for 3 days now 

thank you

**Comment by PrSinister** [comment]
What are you trying to do?

**Comment by PrSinister** [comment]
The <<< and >>> are only if you need to put text there for any reason... completely optional...

Here is a screenshot of my applet in IFTTT that plays movies in the bedroom:

![kodi bedroom kodi play movie name in the bedroom then play the movie ifttt](https://user-images.githubusercontent.com/247870/28299054-f471e688-6b44-11e7-9325-a540355f56d1.png)

**Comment by manofsteel2017** [comment]
PrSinister , i did follow all the steps but when i don't know what to put when it asked me to turn it on. 
I put the token code in that field it does let me turn it on but it doesn't work even though google home took the command. 

Thank you again for the quick reply

**Comment by manofsteel2017** [comment]
![stop](https://user-images.githubusercontent.com/30217010/28318980-9a335034-6b9a-11e7-95b1-6f615dc4a375.PNG)

**Comment by manofsteel2017** [comment]
![screenshot_20170718-193038](https://user-images.githubusercontent.com/30217010/28344169-e16de220-6bef-11e7-808e-26e9eef48b7e.png)
![screenshot_20170718-192958](https://user-images.githubusercontent.com/30217010/28344168-e1695da4-6bef-11e7-8706-085b0b11228a.png)

**Comment by manofsteel2017** [comment]
i do have everything set up by doing your tutorial
this sucks i can't get it to work

**Comment by PrSinister** [comment]
It's not my tutorial but now comes the task of troubleshooting... So you need to first start playing something on kodi and then when the item is playing, go to "http://[YOUR_INTERNAL_KODI_IP:PORT]/stop" and see if it stops. If it doesn't stop then the problem is with your Kodi configuration.

If it does stop, then you need to verify that your router is actually sending the requests to kodi. So you need to go to "http://[YOUR_EXTERNAL_KODI_IP:PORT]/stop". If it doesn't work, you need to look at your Port Triggering/Port Forwarding settings on your router. If it works then it's your glitch app that has the problem. If that's the case, make sure your .env has the right values in there. You can post the contents here if you want some help but remove the token.

If all is well with the glitch app then make sure your IFTTT applet is using the webhook as a GET, application/json and the token is correct.

**Comment by manofsteel2017** [comment]
Ok, i'll try 
and also to turn on the applets what do i put in the field thingy?

**Comment by PrSinister** [comment]
what field thingy?

**Comment by manofsteel2017** [comment]
I can see my kodi menu and whatever is playing with http://[YOUR_EXTERNAL_KODI_IP:PORT]
but when i added /stop it said not found 

maybe i edited the file wrongly 
really wish you made a youtube tutorial 
everyone has old tutorial from 3 years ago

**Comment by manofsteel2017** [comment]
Surround any text with "<<<" and ">>>" to escape the content   
i have to add something before i can actually turn on the applets since it won't turn on without that

**Comment by PrSinister** [comment]
I have no clue what you mean by that... This is getting a bit much for an issue on Github. Let's take this to direct emails... Email me a p r o f e s s o r . s i n i s t e r @ g m a i l . c o m

**Comment by manofsteel2017** [comment]
ok

**Comment by manofsteel2017** [comment]
i emailed you. 
does your email into aprofessor or just professor

**Comment by PrSinister** [comment]
No. My email is:

![pr_email](https://user-images.githubusercontent.com/247870/28347286-31d7aa20-6c04-11e7-9339-de567c80c10f.png)

**Comment by manofsteel2017** [comment]
yeah that's what i emailed you at lol
i figured. hope you can safe me from this nightmare man lol

**Comment by PrSinister** [comment]
weird... haven't received it

**Comment by OmerTu** [comment]
Try pausing a video on Kodi by entering this in your browser:
http://[YOU_KODI_IP]:[PORT]/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Player.playpause","params":{"playerid":1}}

If you get prompt to enter username and password choose the ones you set in Kodi.

**Comment by manofsteel2017** [comment]
emailed again 
and i got this result {"id":1,"jsonrpc":"2.0","result":{"speed":0}}

**Comment by manofsteel2017** [comment]
actually it paused the video and unpaused it too

**Comment by manofsteel2017** [comment]
most of my issue is fixed now sadly i can't get it to play anything 
it does say the command but nothing happened

**Comment by McMoobud** [comment]
Did you try the same Json code as suggested with your EXTERNAL IP? 

I got this all working and setup tonight and once I ran those two tests - I managed to nail it down to a Port forwarding issue, because the JSON code worked on my internal IP and NOT on my external. Turns out my Port Forwarding wasn't setup correctly. I did some troubleshooting with that and once I got the port setup correctly, everything worked. 

Give it a go dude. 

So if THIS works : 

http://INTERNALIP:PORT/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Player.playpause","params":{"playerid":1}}

Try This: 

http://EXTERNALIP:PORT/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Player.playpause","params":{"playerid":1}}

If the first works and the second doesn't - It's a port forwarding issue.

**Comment by manofsteel2017** [comment]
I have an Asus router.
All I did was go to Port forwarding and put the kodi port which is 192.1.1xxx then for port i put port 8080.
It's straight forward

But I don't know if I should put my external ip or the shieldtv/kodi..


The code you posted can pause and play kodi when I put it in browser but not in IFTTT
So I have no clue at all  lol

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by McMoobud** [comment]
External IP Is the up of your router when testing. Then the router should take that info (the port number) and forward it got the shield if the port forward is setup correctly. 

Have you got a router or a modem behind the Asus or just the Asus itself? 

I have a modem behind mine so had to use port forwarding on that rather than my Asus router. Also if the shield is running kodi through an android Os You might find that you'll be limited to external connections. Can't be sure though.

**Comment by manofsteel2017** [comment]
I have a modem and a router.

So  I should open both my shield and external ip?

Idk wish someone would make a YouTube video

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by McMoobud** [comment]
While testing mine I left out IFTTT until I could.get those.Json RPC commands working. Once they worked on both the Ips I went back to IFTTT and the github code

**Comment by McMoobud** [comment]
It would be hard to make a video because it really depends on your setup. 

Sounds very similar to mine tbh. Check your port forwarding settings on your modem as that's what will be catching everything coming in on your external IP. 

Basics flow as I understand it:

1.Google home command comes in and IFTTT Takes it
2.IFTTT sends the command to the web interface on the github repo which in turn send it off to your external IP with the Jason command 
3. Modem received the traffic on the port you've assigned and forwards it to kodi. 
4. Command runs on kodi. 

Seems like your issue is with step 3. Focus on that with the commands I gave you (which are also listed at the bottom of the readme supplied), get those working and everything else should fall into place. 

In the UK So sleep time for me now. Good luck!

**Comment by manofsteel2017** [comment]
Thanks for your reply.
Usually my modem doesn't block anything. It's just a pos modem lol.
But good night

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by McMoobud** [comment]
Have you setup Port forwards for other services? 

Might help to know what and how those are done so I can understand your setup a little more.

**Comment by manofsteel2017** [comment]
I used to hsve one for my ps4. I'm also an IT specialist lol.
So I kinda know things lol

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
