### ISSUE TITLE
Running Docker Image on Libreelec

### ISSUE THREAD

**Issue by stuCONNERS1983** [OmerTu/GoogleHomeKodi#167]
Im trying to setup the docker image on libreelec. I have a question. whats the url in IFTTT? On glitch its https://myglitchaddress/playpause but not using glitch so does that become my external IP? This triggers pause. 

Also when following the instructions I get this error when trying to launch the docker container:  Error starting userland proxy: listen tcp 0.0.0.0:8099: bind: address already in use.

I have a MariaDB container setup: f98cc7bd9a19        mariadb:latest          "docker-entrypoint..."   3 days ago          Up 11 hours                0.0.0.0:3306->3306/tcp   mariadb

How would I stop them from conflicting? Also do I have to expose the webserver to the internet? Currently its blocked via a VPN. Im hoping that running this docker version will allow it to work behind a VPN. Any help is great cheers.

**Comment by stuCONNERS1983** [comment]
When running "netstat -pna | grep 8099" I get:
tcp 0 0 :::8099 :::* LISTEN 958/hyperiond

I have hyperion running on the same box, is this conflicting with it? Ive asked on the libreelec forum about this issue https://forum.libreelec.tv/thread/12911-docker-google-home/

**Comment by keydon** [comment]
Well, if you don't want to expose this app to the internet, how do you expect IFTTT to be able to reach your app instance in order to relay the spoken commands? 
And for the port issue, you can only have one app running on a single port. Just change the port if it's already used by another app by replacing `-p 8099:8099` with `-p 8077:8099` for i.e. port 8077.

**Comment by stuCONNERS1983** [comment]
I wasn't sure if it worked like the nodejs. Anyway ive sorted this out now.
