### ISSUE TITLE
Feature Request: Recognise HTTPS for Reverse Proxy

### ISSUE THREAD

**Issue by Y05H10** [OmerTu/GoogleHomeKodi#23]
Greetings,

I'm running an Nginx Reverse Proxy for Kodi's JsonRPC.
e.g. https://media.example.com/jsonrpc
so that my JSONRPC is behind SSL.

My Env File reflects this :
```
KODI_IP="media.example.com"
KODI_PORT="443"
KODI_USER="YOUR_KODI_USER_NAME"
KODI_PASSWORD="YOUR_KODI_PASSWORD"
AUTH_TOKEN="THISISNTEVENMYREALPASSWORD"
```

However the Request from the Glitch Project will still be Plain HTTP.

```
Request token = THISISNTEVENMYREALPASSWORD
2:58 PM
Authentication succeeded
2:58 PM
Movie request received to play "Matrix"
2:58 PM
Command sent = {"jsonrpc":"2.0","id":1,"method":"VideoLibrary.GetMovies"}
2:58 PM
{ FetchError: invalid json response body at http://media.example.com:443/jsonrpc reason: Unexpected token < in JSON at position 0
2:58 PM
    at /app/node_modules/node-fetch/lib/body.js:48:31
2:58 PM
    at process._tickCallback (internal/process/next_tick.js:109:7)
2:58 PM
  name: 'FetchError',
2:58 PM
  message: 'invalid json response body at http://media.example.com:443/jsonrpc reason: Unexpected token < in JSON at position 0',
2:58 PM
  type: 'invalid-json' }
2:58 PM
```

So i changed the Kodi function is api.js …
```
  function Kodi(ip, port, username, password) {
    kodi_auth = 'Basic ' + new Buffer(username + ':' + password).toString('base64');
    this.url = 'http://' + ip + ':' + port + '/jsonrpc';
    addMethods(this);
  }
```
… to use https instead
`this.url = 'https://' + ip + ':' + port + '/jsonrpc';`

Would be nice to have an env to set the protocol or some other mean to make it easier for newcomers.

**Comment by whitter** [comment]
Just found this cool app.  You can skip the need to expose Kodi to the internet (i.e. do not use Glitch.com) if you run the app on your local computer/server. You can then just reverse proxy to your locally running instance of GoogleHomeKodi, and configure IFTTT to call your reverse proxy instead of the Glitch.com URL.  Also means you don't have to store your Kodi username and password on another service.

Just need to:
1. Install Node if you dont have it
2. Clone this repo
3. Install the Node packages for the server, npm install
4. Create a file called .env
5. Added all the settings from the setup guide:
KODI_IP="YOUR_EXTERNAL_IP_ADDRESS"
KODI_PORT="YOUR_KODI_PORT"
KODI_USER="YOUR_KODI_USER_NAME"
KODI_PASSWORD="YOUR_KODI_PASSWORD"
AUTH_TOKEN="YOUR_CONNECTION_PASSWORD"
6. Add an extra setting called PORT, this is the port number you want GoogleHomeKodi to run on locally

**Comment by Auto-m8r** [comment]
@whitter,

Can you add step by step instructions on how to perform the above setup? I'm keen to also secure my Kodi connections so passwords are not sent in plain text across the internet.

**Comment by whitter** [comment]
@Auto-m8r Yeah sure.  What bit would you need more info on? Setting up and running the GoodleHomeKodi instance, setting up a secure reverse proxy (if it is this bit what web server would you be configuring the reverse proxy in?) or the then configuring IFTTT?

**Comment by Auto-m8r** [comment]
@whitter,

Probably both :-)... I'm not super experienced on this.

I currently run a Raspberry Pi with Kodi in my living room, ideally I would like to add th reverse proxy here if I can. Node is installed as I also have Homebridge, Airsonos and Node-Sonos-Http-Api running on it as well so I have that part setup.

ideally being a novice at this stuff a walkthrough based on setting up the whole thing on a raspberry pi would be super useful.

thanks in advance

**Comment by siaox** [comment]
Any thing for Json script for updating the library ?
