### ISSUE TITLE
Phrase broker docker

### ISSUE THREAD

**Issue by jollybully** [OmerTu/GoogleHomeKodi#237]
Can we expect to see the phrase broker implemented into the official docker container? Seems like a more appropriate of maintaining any intent enhancements moving forward. Great work as ever!

**Comment by keydon** [comment]
the broker feature is already in the docker image from day one. So no idea what you are talking about.

I personally dont recommend the broker approach, since googles recognition has no knowledge about the possible phrases and therefore cannot optimize for those phrases. A huge disadvantage in my opinion.
