### ISSUE TITLE
New Google Local Home SDK

### ISSUE THREAD

**Issue by Dnkhatri** [OmerTu/GoogleHomeKodi#251]
https://github.com/actions-on-google/smart-home-local

Looks like google is opening up google home to access local network devices directly. This should allow for direct control rather than through ifttt and bring down latency make it instant.

**Comment by keydon** [comment]
did you take a more closer look on this topic?
last I checked I came to the conclusion its very limited to specific device types and traits (https://developers.google.com/assistant/smarthome/concepts/devices-traits)
and for a powerful media player like kodi we could maybe only use the on and off intents xD
And since kodi is kinda a competitor for googles chromecast and android tv, I dont think they will add stuff for us :)
