### ISSUE TITLE
kodi play youtube stopped working?

### ISSUE THREAD

**Issue by Brad3rs** [OmerTu/GoogleHomeKodi#303]
maybe it's me but Kodi play youtube $ stopped working and i didnt touch anything.
i get a 500 error at ifttt or a webhooks error

```
Applet skipped
Jun 07 - 5:46 PM
Google Assistant
If You say "Kodi play youtube $", then Make a web request
Unable to make web request. Your server returned a 500
Hide details
Ingredients
CreatedAt
June 7, 2020 at 05:46PM
TextField
Scooby - Doo
```

earlier in the month it said
There was a problem with the Webhooks service.

```
Applet failed
May 29 - 10:09 PM
Google Assistant
If You say "Kodi play youtube $", then Make a web request
There was a problem with the Webhooks service.
```

all other googlehomekodi commands and ifttt applets work fine, volume, tv off etc even the search youtube command works

is it a webhooks error? or have YouTube changed something as it only seems to happen with that applet?
as i said i haven't changed anything since it was working.
it would be helpful to know if it's just me
i'm using docker and pi3's with libreelec
thanks for your help.

**Comment by keydon** [comment]
yeah I can confirm that its broken right now. Now sure why thou. Maybe the api-key got invalidated by google.

**Comment by Brad3rs** [comment]
thanks for taking a look, it's a great feature, probably the best one,
hope it won't be long till you can sort it 👍

**Comment by keydon** [comment]
well I am clueless. Changed the youtube-library we use, generated new api-keys but it is still broken. Looks like the google-api is down to me, but thats impossible ;O

**Comment by keydon** [comment]
found the culprit, the api seems not to like on of the old parameter values any longer! fix will be available shortly!

**Comment by keydon** [comment]
it was the api-key after all.
my new one needed some time to be activated I guess and the new library I use now prints a proper error message
`The request cannot be completed because you have exceeded your quota.`
mmmh what can we do about that. not sure if I want to use the key of my personal account :D
But you guys are welcome to generate a key for yourself and use that instead. Its free and help the public-quota I guess ;o
Howto: https://www.slickremix.com/docs/get-api-key-for-youtube/
Configure it either through the environment variable `YOUTUBE_KEY` or in `kodi-hosts.config.js` at `youtubeKey`

**Comment by keydon** [comment]
hmm it seems regular keys like ours have a daily 10.000 credits limit for youtube.
A search request like ours seems to cost 100 credits.
![image](https://user-images.githubusercontent.com/2421541/85208433-c4d02980-b330-11ea-8148-ddea19902ed5.png)


That means that as a community we can have just 100 requests per day together! It seems we keep reaching the limit. (assuming no one stole that key for other purposes)
We can try to apply for an increase of the quota limit. Also I can try to optimize the request we send in order to save resources. But the docs are not clear on that topic.
Since the current key is not mine and I have no information about the actual usage I will replace that with a key of mine, after having optimized the requests. I still encourage you to generate your own key and use that instead.

**Comment by Brad3rs** [comment]
thanks for your help i have an api key, i think the Kodi YouTube app required we generated our own ages ago because of the same quota issue, so i can use that but wasn't sure where to put it. thanks for sorting it out 👍 works perfectly again 😀

**Comment by talondnb** [comment]
May I ask what was sorted out with this? I still can't seem to perform 'kodi youtube' requests at the moment yet everything else works fine. I already have my own API too.

**Comment by talondnb** [comment]
Nevermind, I hadn't read the fix earlier on.

For those who hadn't noticed like myself:

> Configure it either through the environment variable `YOUTUBE_KEY` or in `kodi-hosts.config.js` at `youtubeKey`
