### ISSUE TITLE
[Fix README.md] - mute, play next unwatched episode of a TV show

### ISSUE THREAD

**Issue by madmax2** [OmerTu/GoogleHomeKodi#317]
**Change volume:
Mute kodi: "Hey Google, mute/unmute kodi"**

This would not work..since there is no unmute command that kodi would recognize
Kodi only knows the command mute which toggles the mute or unmute.

Change to

**Mute/unmute kodi: "Hey Google, kodi mute"**

-------------------
Action table 

Say a simple phrase | Kodi mute | YOUR_NODE_SERVER/mute
-- | -- | --

to 

Say a simple phrase | Kodi mute [note: to unmute, issue same command]  | YOUR_NODE_SERVER/mute
-- | -- | --

--------------------
Say a simple phrase | Kodi pause | YOUR_NODE_SERVER/playpause
-- | -- | --

to

Say a simple phrase | Kodi pause [note: to unpause, issue same command | YOUR_NODE_SERVER/playpause
-- | -- | --

-------
**Play the next unwatched episode: "Hey Google, kodi play tv show [tv show name]" --> will search for the given tv show and play the next unwatched episode.**

to

**Play the next unwatched episode: "Hey Google, kodi play an episode of [tv show name]" --> will search for the given tv show and play the next unwatched episode.**

**Comment by madmax2** [comment]
@keydon hey why did you add the command
-unmute to the action table?

I tested the unmute command and kodi does not recognize it in the log terminal.

`==== BEGIN === route:  /broker
Broker processing phrase: 'unmute' (en)
request failed
route:  /broker
query:  { phrase: 'unmute' }
error:  Error: Broker unknown phrase: 'unmute' (en)`

**Comment by keydon** [comment]
Well the action table is not there to document the broker phrases.
It lists all endpoints with a suggested phrase, that is the original one IFTTT-applet per command approach.


The broker phrases match mostly the expample phrases of the action-table but they itself are not explicitly documented.
You can look them up in the code [here](https://github.com/OmerTu/GoogleHomeKodi/blob/master/broker/en.json), but they are not easy to read, since they are written in a powerful regex-notation. More understandable, but far from complete are the [tests](https://github.com/OmerTu/GoogleHomeKodi/blob/master/test/broker/en.json).

I also now added "unmute" to the broker.
