### ISSUE TITLE
WebHooks not working.

### ISSUE THREAD

**Issue by Cribz679** [OmerTu/GoogleHomeKodi#33]
Hi,

I am having issues with this. I have setup everything correctly. My port forwaring is setup correctly as well. I am able to execute Kodi json commands via another internet source using my external IP, however when doing this via IFTTT Google Assistant >> Webhooks I get no results. Appreciate anyone's assistance. 

Thanks

**Comment by p0psicles** [comment]
Do you still need help on this?

**Comment by NellyJelly** [comment]
This sounds exactly like the problem I'm having. I could do with some help with it. If Cribz679 found answear to the questions could you share it please

**Comment by p0psicles** [comment]
Please share the logs. It should provide you with some info if the call from ifttt.com to glitch.com works. More info you provide, better we can help you.

**Comment by NellyJelly** [comment]
Which log,  from kodi??

**Comment by NellyJelly** [comment]
log from glitch

👳 Your app is listening on port 3000
3:23 PM
8 minutes ago
node v6.10.3, npm 3.10.10
3:37 PM
Installing...
3:37 PM
8 minutes ago
node v6.10.3, npm 3.10.10
3:37 PM
Installing...
3:37 PM
8 minutes ago
🌋🕹 Your app is listening on port 3000
3:37 PM

**Comment by NellyJelly** [comment]
Tried turning off VPN and running applet again this is kodi log.
4:52:18.562 T:139907781650176  NOTICE: VPN Mgr : (common.py) Received connection info from ipinfo.io, IP  location Akershus, NO, ISP AS41164 Get AS
14:52:18.562 T:139907781650176  NOTICE: VPN Mgr : (common.py) Disconnected from the VPN
14:54:28.635 T:139909579623744  NOTICE: Log level changed to "LOG_LEVEL_DEBUG_FREEMEM"
14:54:28.635 T:139909579623744  NOTICE: Enabled debug logging due to GUI setting. Level 2.
14:54:28.635 T:139909579623744   DEBUG: ------ Window Init () ------
14:54:31.338 T:139907756472064   DEBUG: CWebServer[8080]: request received for /jsonrpc

**Comment by p0psicles** [comment]
Glitch should provide more info then that. So I think the webhook is not reaching glitch nodejs server.

**Comment by NellyJelly** [comment]
ok how can i fix that or where should i be looking to fix it

**Comment by p0psicles** [comment]
That last log shows your kodi ip address is not configured correct. I guess your using the .env file. Check that file again.

Also if you check out lastest develop branch. There is a new route added `/koditestconnection`. That provides more debug logs. Try that.

**Comment by NellyJelly** [comment]
I took away last digits from  ip address for I posted it ..
Will check out latest develop branch

**Comment by keydon** [comment]
Closed due to inactivity
