### ISSUE TITLE
Docker + Multi Instance + Phrase Broker

### ISSUE THREAD

**Issue by gibben1971** [OmerTu/GoogleHomeKodi#348]
I am having issues trying to get a multi Kodi setup working from a single server setup using phrase broker. I'm sure I'm missing something or it's just beyond my paygrade:
My Setup:
Docker Desktop running on Windows 10 - Single Instance (Option B3) - I'm building with the use of a config file. This is the first concern, when it builds docker prompts a desktop warning about using an external file.
![ts6](https://user-images.githubusercontent.com/88373342/127986426-59040143-d6bf-4690-a370-20dad694469a.PNG)

I am using separate IFTT applets for each instance, the triggers are the same for each one 
![ts4](https://user-images.githubusercontent.com/88373342/127986650-1e27b394-99f6-491e-854d-7de871a59a7c.PNG)
 
However for the action on each applet, in the body  I have inserted the id of the kodi instance to match 
![ts5](https://user-images.githubusercontent.com/88373342/127986972-384a2db6-8102-4b73-8cf5-4159ada95c42.PNG)
 
Regardless, the commands always get sent to the same Kodi box (which happens to be the first one in the config file. Also noting complex commands don't seem to work. If I disable all applets except for one, and remove the id in the body, then everything works fine just firing to a single  box.

So, I'm officially stumped ... I've attached some output screens as well.
![TS1](https://user-images.githubusercontent.com/88373342/127987675-484dc896-1c77-466c-b415-e5193ec727d1.PNG)
![ts2](https://user-images.githubusercontent.com/88373342/127987716-a5e3a4d5-2b47-4b7c-93bd-ff11ffe4b8bd.PNG)
![ts3](https://user-images.githubusercontent.com/88373342/127987743-edb71b2b-d116-4755-94bb-a69f64db2064.PNG)

**Comment by keydon** [comment]
>  am using separate IFTT applets for each instance, the triggers are the same for each one

thats the issue right there. the trigger phrases need to be different. We need the information, which kodi instance you want to target within the trigger. i.e `living room kodi $`

> complex commands don't seem to work

According to the log-snippets you seem to encode the target-kodi at the end of a phrase. i.e. `in the lounge` or `in the family`.
but your IFTTT-Trigger does not reflect that. Thats why most command wont work, since the broker get thrown off by those words.

You could try to mix the recommend approch with your approach, if it feels more natural to you. But I am not sure if it will work well. Meaning you could make your trigger phrase like this: `kodi $ in the lounge` and `kodi $ in the family`
IFTTT should then only pass on the desired `$`-payload together with the kodi-ID. Then the broker should be happy.

> docker prompts a desktop warning about using an external file

thats to be expected on windows, if you use the external file approach.

**Comment by gibben1971** [comment]
Appreciate the quick response, I'll make some changes tonight and feedback how I go.

**Comment by keydon** [comment]
timeout -> closed. Please open a new issue, if you still have problems.
