### ISSUE TITLE
Start making proper releases

### ISSUE THREAD

**Issue by keydon** [OmerTu/GoogleHomeKodi#72]
hey guys,

this is more of a discussion thread than an issue.

soner or later we will have to make some breaking changes to the api.
to be able to communicate such changes it would be wise to habe proper releases with version numbers and a summary of changes made in that release.

breaking api changes i think might come:
* drop the support of query-paramters (supporting both, query-params and a json-body makes not much sense to me)
* cluster the routes insead of having them layed out flat, like /navigation/* (could then be refactored out in seperate express-sub-apps)
* having /mute, /unmute and /toggleMute instead of just /mute which doesnt actually _mute_ but just toggels it.

**Comment by p0psicles** [comment]
We've got a slack, do you want to join it?

**Comment by keydon** [comment]
sure, would love to :d

**Comment by p0psicles** [comment]
I need to add your email

**Comment by keydon** [comment]
well just add an @gmail.com to my nickname and you are good to go :d

**Comment by warlord0** [comment]
I find it useful to have both query params and body just because it makes editing the IFTTT easier.

I can leave alone the body with just the token in and the only change is in the query params.

It also makes little difference with /mute. In the IFTTT I just have other ways of saying the same thing "kodi mute" "kodi unmute" both on one applet. But if you're going for releases you should consider users who already have it deployed and may stumble into a wall of depreciated functions.

Just my 2c.
